version: 2

models:

  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: dim_merchant
    columns:
      - name: merchant_id
        tests:
          - not_null
          - unique

  - name: dim_state
    columns:
      - name: state
        tests:
          - not_null
          - unique

  - name: fact_transactions
    columns:

      - name: transaction_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id

      - name: merchant_id
        tests:
          - relationships:
              to: ref('dim_merchant')
              field: merchant_id

      - name: state
        tests:
          - relationships:
              to: ref('dim_state')
              field: state
